# Generated by Django 4.2.3 on 2023-07-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20, unique=True)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("phonenumber", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                (
                    "log_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Djapplication.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("phonenumber", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("post", models.CharField(max_length=20)),
                ("pincode", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                (
                    "log_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Djapplication.log",
                    ),
                ),
            ],
        ),
    ]
