# Generated by Django 4.2.3 on 2023-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Djapplication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phonenumber",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="email",
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="phonenumber",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
