# Generated by Django 4.2.3 on 2023-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Djapplication", "0002_alter_log_password_alter_student_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="username",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="pincode",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="address",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="email",
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="username",
            field=models.CharField(max_length=40),
        ),
    ]
