# Generated by Django 4.2.3 on 2023-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Djapplication", "0003_alter_log_username_alter_student_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=20)),
            ],
        ),
    ]
