# Generated by Django 4.2.3 on 2023-09-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Djapplication", "0004_otp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Otp",
        ),
    ]
