# Generated by Django 4.2.3 on 2023-09-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Djapplication", "0005_delete_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
    ]
